[package]
name = "safekeeper_client"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
safekeeper_api.workspace = true
thiserror.workspace = true
reqwest = { workspace = true, features = [ "stream" ] }
serde.workspace = true
utils.workspace = true
workspace_hack = { version = "0.1", path = "../../workspace_hack" }
