[package]
name = "zenith_metrics"
version = "0.1.0"
edition = "2018"

[dependencies]
prometheus = {version = "0.12", default_features=false} # removes protobuf dependency
libc = "0.2"
lazy_static = "1.4"
once_cell = "1.8.0"
