[package]
name = "pageserver_page_api"
version = "0.1.0"
edition = "2024"

[dependencies]

# For Lsn.
#
# TODO: move Lsn to separate crate? This draws in a lot more dependencies
utils.workspace = true

prost.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tonic.workspace = true

[build-dependencies]
tonic-build.workspace = true
