storage:
  vars:
    bucket_name: neon-prod-storage-us-west-2
    bucket_region: us-west-2
    console_mgmt_base_url: http://neon-internal-api.aws.neon.tech
    broker_endpoint: http://storage-broker-lb.eta.us-west-2.internal.aws.neon.tech:50051
    pageserver_config_stub:
      pg_distrib_dir: /usr/local
      metric_collection_endpoint: http://neon-internal-api.aws.neon.tech/billing/api/v1/usage_events
      metric_collection_interval: 10min
      disk_usage_based_eviction:
        max_usage_pct: 85 # TODO: decrease to 80 after all pageservers are below 80
        min_avail_bytes: 0
        period: "10s"
      tenant_config:
        eviction_policy:
          kind: "LayerAccessThreshold"
          period: "10m"
          threshold: &default_eviction_threshold "24h"
        evictions_low_residence_duration_metric_threshold: *default_eviction_threshold
      remote_storage:
        bucket_name: "{{ bucket_name }}"
        bucket_region: "{{ bucket_region }}"
        prefix_in_bucket: "pageserver/v1"
    safekeeper_s3_prefix: safekeeper/v1/wal
    hostname_suffix: ""
    remote_user: ssm-user
    ansible_aws_ssm_region: us-west-2
    ansible_aws_ssm_bucket_name: neon-prod-storage-us-west-2
    console_region_id: aws-us-west-2-new
    sentry_environment: production

  children:
    pageservers:
      hosts:
        pageserver-0.us-west-2.aws.neon.tech:
          ansible_host: i-0d9f6dfae0e1c780d
        pageserver-1.us-west-2.aws.neon.tech:
          ansible_host: i-0c834be1dddba8b3f
        pageserver-2.us-west-2.aws.neon.tech:
          ansible_host: i-051642d372c0a4f32
        pageserver-3.us-west-2.aws.neon.tech:
          ansible_host: i-00c3844beb9ad1c6b
        pageserver-4.us-west-2.aws.neon.tech:
          ansible_host: i-013263dd1c239adcc
        pageserver-5.us-west-2.aws.neon.tech:
          ansible_host: i-00ca6417c7bf96820
        pageserver-6.us-west-2.aws.neon.tech:
          ansible_host: i-01cdf7d2bc1433b6a
        pageserver-7.us-west-2.aws.neon.tech:
          ansible_host: i-02eec9b40617db5bc

    safekeepers:
      hosts:
        safekeeper-0.us-west-2.aws.neon.tech:
          ansible_host: i-00719d8a74986fda6
        safekeeper-1.us-west-2.aws.neon.tech:
          ansible_host: i-074682f9d3c712e7c
        safekeeper-2.us-west-2.aws.neon.tech:
          ansible_host: i-042b7efb1729d7966

