storage:
  vars:
    bucket_name: neon-prod-storage-ap-southeast-1
    bucket_region: ap-southeast-1
    console_mgmt_base_url: http://console-release.local
    broker_endpoint: http://storage-broker-lb.epsilon.ap-southeast-1.internal.aws.neon.tech:50051
    pageserver_config_stub:
      pg_distrib_dir: /usr/local
      remote_storage:
        bucket_name: "{{ bucket_name }}"
        bucket_region: "{{ bucket_region }}"
        prefix_in_bucket: "pageserver/v1"
    safekeeper_s3_prefix: safekeeper/v1/wal
    hostname_suffix: ""
    remote_user: ssm-user
    ansible_aws_ssm_region: ap-southeast-1
    ansible_aws_ssm_bucket_name: neon-prod-storage-ap-southeast-1
    console_region_id: aws-ap-southeast-1
    sentry_environment: production

  children:
    pageservers:
      hosts:
        pageserver-0.ap-southeast-1.aws.neon.tech:
          ansible_host:  i-064de8ea28bdb495b
        pageserver-1.ap-southeast-1.aws.neon.tech:
          ansible_host:  i-0b180defcaeeb6b93

    safekeepers:
      hosts:
        safekeeper-0.ap-southeast-1.aws.neon.tech:
          ansible_host:  i-0d6f1dc5161eef894
        safekeeper-1.ap-southeast-1.aws.neon.tech:
          ansible_host:  i-0e338adda8eb2d19f
        safekeeper-2.ap-southeast-1.aws.neon.tech:
          ansible_host:  i-04fb63634e4679eb9
